name: 'Entur/Security/Code Scan'

on:
  workflow_call:

env:
  GITHUB_REPOSITORY: ${{ github.repository }}
  GIT_REF: ${{ github.ref }}

jobs:
  upload-cached-results:
    runs-on:  ubuntu-24.04
    permissions:
      pull-requests: read
      actions: read
      security-events: write
      contents: write 
    steps:
      - name: "Get workflow run ID for matching PR"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_SHA: ${{ github.sha }}
        run: |
          HEAD_REF=$(gh pr list --state merged --search "$GITHUB_SHA" --json headRefOid -R "$GITHUB_REPOSITORY" | jq -r '.[0].headRefOid')
          if [ "$HEAD_REF" = "null" ]; then
            echo "::warning ::Failed to fetch closed PRs, defaulting to running a new scan"
            echo 'GHA_SECURITY_CODE_SCAN_SKIP_JOB_AND_CONTINUE_SCAN=True' >> "$GITHUB_ENV"
          else
            JOB_ID=$(gh run list -s completed -e pull_request -c "$HEAD_REF" --json databaseId -R "$GITHUB_REPOSITORY" -w ".github/workflows/codeql.yml" | 
              jq -r '.[0].databaseId')
            if [ "$JOB_ID" = "null" ]; then
              echo '::warning ::Failed to find a matching job, defaulting to running a new scan'
              echo 'GHA_SECURITY_CODE_SCAN_SKIP_JOB_AND_CONTINUE_SCAN=True' >> "$GITHUB_ENV"
            else
              echo "GHA_SECURITY_CODE_SCAN_WORKFLOW_RUN_ID=$JOB_ID" >> "$GITHUB_ENV"
            fi
          fi

      - name: "Download existing cached results from previous job (pr)"
        uses: actions/download-artifact@v7
        with:
          run-id: ${{ env.GHA_SECURITY_CODE_SCAN_WORKFLOW_RUN_ID }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path: "/home/runner/work/${{ env.GITHUB_REPOSITORY }}/results"

      - name: "Upload scan results"
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: "/home/runner/work/${{ env.GITHUB_REPOSITORY }}/results"
          category: 'scan-results'

      - name: "Upload dependency graph"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_SHA: ${{ github.sha }}
          GITHUB_REF: ${{ github.ref }}
        run: |
          shopt -s globstar nullglob
          for file in "/home/runner/work/$GITHUB_REPOSITORY/results"/**/*.json ; do
            if [ -d "$file" ] ; then
              continue
            fi
            jq ".sha = \"$GITHUB_SHA\" | .ref = \"$GITHUB_REF\"" < "$file" | 
              gh api "/repos/$GITHUB_REPOSITORY/dependency-graph/snapshots" --method POST --input -
          done
